//
// Created by DScho on 2022/10/15.
//

#ifndef OPTIMAL_CIRCUITRY_COS_214_PROJECT_CONCRETECOUNTRYFACTORY_H
#define OPTIMAL_CIRCUITRY_COS_214_PROJECT_CONCRETECOUNTRYFACTORY_H
#include "countryFactory.h"


class concreteCountryFactory : countryFactory {

};


#endif //OPTIMAL_CIRCUITRY_COS_214_PROJECT_CONCRETECOUNTRYFACTORY_H
