//
// Created by DScho on 2022/10/28.
//

#ifndef OPTIMAL_CIRCUITRY_COS_214_PROJECT_MILITARYFACTORY_H
#define OPTIMAL_CIRCUITRY_COS_214_PROJECT_MILITARYFACTORY_H


class militaryFactory {

};


#endif //OPTIMAL_CIRCUITRY_COS_214_PROJECT_MILITARYFACTORY_H
